// <auto-generated />
using ManyToManyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManyToManyAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.Property<int>("CoursesCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CoursesCourseId", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            CoursesCourseId = 101,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            CoursesCourseId = 102,
                            StudentsStudentId = 1
                        },
                        new
                        {
                            CoursesCourseId = 103,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            CoursesCourseId = 104,
                            StudentsStudentId = 2
                        },
                        new
                        {
                            CoursesCourseId = 105,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            CoursesCourseId = 101,
                            StudentsStudentId = 3
                        },
                        new
                        {
                            CoursesCourseId = 102,
                            StudentsStudentId = 4
                        },
                        new
                        {
                            CoursesCourseId = 103,
                            StudentsStudentId = 4
                        },
                        new
                        {
                            CoursesCourseId = 104,
                            StudentsStudentId = 5
                        },
                        new
                        {
                            CoursesCourseId = 105,
                            StudentsStudentId = 5
                        });
                });

            modelBuilder.Entity("ManyToManyAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 101,
                            CourseName = "Programming 2231",
                            Credits = 3,
                            Description = "Intro to programming"
                        },
                        new
                        {
                            CourseId = 102,
                            CourseName = "Database System",
                            Credits = 3,
                            Description = "Learn about No sql"
                        },
                        new
                        {
                            CourseId = 103,
                            CourseName = "Data Structures and Algorithms",
                            Credits = 3,
                            Description = "Learn about DSA"
                        },
                        new
                        {
                            CourseId = 104,
                            CourseName = "Agile System",
                            Credits = 3,
                            Description = "Learn about Agile"
                        },
                        new
                        {
                            CourseId = 105,
                            CourseName = "Cyber security",
                            Credits = 3,
                            Description = "Learn about security"
                        });
                });

            modelBuilder.Entity("ManyToManyAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Major")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "mj@gmail.com",
                            Major = "CPA",
                            Name = "MJ Han"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "eunwoo@gmail.com",
                            Major = "CP",
                            Name = "Eunwoo Cha"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "lucas@gmail.com",
                            Major = "CPA",
                            Name = "Lucas Lee"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "mina@gmail.com",
                            Major = "CP",
                            Name = "Mina Lee"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "seonmi@gmail.com",
                            Major = "CPA",
                            Name = "Seonmi Kang"
                        });
                });

            modelBuilder.Entity("Enrollment", b =>
                {
                    b.HasOne("ManyToManyAPI.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManyToManyAPI.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
